# ----- font -----
font=FiraCode Nerd Font:size=12

# ----- layout -----
width=35
lines=6
prompt=▌
inner-pad=4
horizontal-pad=24
vertical-pad=4
line-height=24

# ----- colors -----
[colors]
background=000000ff
text=bb88ffff
prompt=8833ffff
input=bb88ffff
placeholder=442266ff
match=ddaaffff
selection=1a0033ff
selection-text=ddaaffff
selection-match=ddaaffff
border=7733ccff
counter=442266ff

# ----- border -----
[border]
width=2
radius=6
