# core

confirm_os_window_close 0
sync_to_monitor yes
enable_audio_bell no
linux_display_server wayland
wayland_enable_ime no
font_size 12.0

# performance

repaint_delay 4
input_delay 0

# url

url_color #f5c2e7
url_style curly
open_url_with default
detect_urls yes
underline_hyperlinks hover

# clipboard

copy_on_select yes
map ctrl+v paste_from_clipboard
map ctrl+c copy_and_clear_or_interrupt

# navigation

map ctrl+t new_tab
map ctrl+w close_tab
map ctrl+right next_tab
map ctrl+left previous_tab

# scroll

map ctrl+up scroll_line_up
map ctrl+down scroll_line_down
map ctrl+page_up scroll_page_up
map ctrl+page_down scroll_page_down

# zoom

map ctrl+equal change_font_size all +2.0
map ctrl+plus change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0

# fonts

font_family Noto Sans Lao Looped Condensed
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

font_features JetBrainsMonoNF-Regular +liga +calt
font_features JetBrainsMonoNF-Bold +liga +calt
modify_font cell_height 115%
modify_font underline_position 2
modify_font underline_thickness 150%
undercurl_style thin-sparse

# cursor

cursor #f5c2e7
cursor_text_color #20121c
cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0
cursor_trail 0
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# window

window_padding_width 15
hide_window_decorations yes
draw_minimal_borders yes
window_border_width 1px
active_border_color #f5c2e7
inactive_border_color #2d1827

# tabs

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_align left
tab_bar_min_tabs 2
tab_activity_symbol none
bell_on_tab no

active_tab_foreground #20121c
active_tab_background #f5c2e7
active_tab_font_style bold
inactive_tab_foreground #b88da5
inactive_tab_background #2d1827
tab_bar_background #20121c

# colors

foreground #f8e1ec
background #20121c
background_opacity 0.92
background_blur 15

selection_foreground #20121c
selection_background #f5c2e7

color0  #2d1827
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #f5c2e7
color5  #f4a8cb
color6  #89dceb
color7  #f8e1ec

color8  #633353
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #f5c2e7
color13 #f4a8cb
color14 #89dceb
color15 #ffffff

# misc

map alt+enter new_window_with_cwd
map alt+c close_tab

allow_remote_control yes
listen_on unix:/tmp/kitty_socket
