# ─────────── playback ───────────
SPACE cycle pause
MBTN_RIGHT cycle pause
q quit-watch-later
o show-progress

# ─────────── seek ───────────
LEFT seek -1 exact
RIGHT seek 1 exact
DOWN seek -5 exact
UP seek 5 exact
MBTN_LEFT cycle pause
TAB seek 85 exact

# ─────────── speed ───────────
[ add speed -0.25
] add speed 0.25
BS set speed 1.0
Ctrl+WHEEL_UP add speed 0.25
Ctrl+WHEEL_DOWN add speed -0.25

# ─────────── volume ───────────
m cycle mute
- add volume -5
= add volume 5
WHEEL_UP add volume 1
WHEEL_DOWN add volume -1

# ─────────── playlist ───────────
i script-binding stats/display-stats-toggle
a playlist-prev
d playlist-next
Ctrl+l playlist-shuffle
Ctrl+r playlist-unshuffle
DEL run "/bin/sh" "-c" "gio trash '${path}'" ; playlist-remove current
. frame-step
, frame-back-step

# ─────────── video ───────────
f cycle fullscreen

# ─────────── screenshot ───────────
s screenshot
Ctrl+s screenshot video

# ─────────── subtitle ───────────
b cycle sub-visibility
B cycle sub

