# ─────────── general ───────────
input-default-bindings=no
autocreate-playlist=filter
loop-playlist=inf
cursor-autohide=1000
autofit-larger=90%x90%

# ─────────── streaming ───────────
cache=yes
cache-secs=30
demuxer-max-bytes=1GiB
demuxer-readahead-secs=300
demuxer-max-back-bytes=500MiB
ytdl-format=bestvideo[height<=720]+bestaudio/best[height<=720]
load-unsafe-playlists=yes
ytdl-raw-options=sub-lang="en.*",write-auto-sub=,compat-options="prefer-vp9-sort"

# ─────────── video ───────────
hwdec=auto-safe

# ─────────── audio ───────────
volume=80
audio-file-auto=fuzzy
volume-max=110
audio-pitch-correction=yes
#alang=en,eng
# ─────────── subtitles ───────────
slang=en,eng
sub-auto=fuzzy
demuxer-mkv-subtitle-preroll=yes
sub-fix-timing=no
sub-font='Open Sans'
sub-font-size=40
sub-color='#FFFFFFFF'
sub-border-color="#FF000000"
sub-shadow-color=0.0/0.0/0.0/0.70
sub-border-size=2.0
sub-shadow-offset=0.75
sub-spacing=0.0
sub-bold=yes
sub-use-margins=no
sub-gauss=0.05
blend-subtitles=video

# ─────────── screenshot ───────────
screenshot-format=jpg
screenshot-jpeg-quality=90
screenshot-dir=~/0/pictures/mpv
screenshot-template="%02n. %F-%wH.%wM.%wS"

# ─────────── resume ───────────
save-position-on-quit=yes

# ─────────── socket ───────────
input-ipc-server=~/.config/mpv-socket
