# network | network: wifi or dns"
# wifi | network manager
# dns | set dns servers
# ─────────── network ───────────
function network -d "Network: WiFi or DNS"
    set -l PURPLE (set_color cba6f7)
    set -l DIM (set_color brblack)
    set -l RESET (set_color normal)

    echo "$PURPLE󰛳 Network$RESET"
    echo "$DIM────────────────────────────$RESET"
    echo "  [1] 󰤨 WiFi"
    echo "  [2] 󰉋 DNS"
    echo "$DIM  [0] 󰜺 exit$RESET"
    echo ""
    read -P "→ choice: " choice

    switch $choice
        case 1
            wifi
        case 2
            dns
        case '*'
            echo "󰜺 cancelled"
    end
end
# ─────────── DNS ───────────
function dns -d "Set DNS servers"
    if test (count $argv) -eq 0
        set -l options \
            "Mullvad|194.242.2.2 194.242.2.3" \
            "Quad9|9.9.9.9 149.112.112.112" \
            "AdGuard|94.140.14.14 94.140.15.15" \
            "Cloudflare|1.1.1.1 1.0.0.1" \
            "Google|8.8.8.8 8.8.4.4"

        while true
            set -l GREEN (set_color green)
            set -l DIM (set_color brblack)
            set -l RESET (set_color normal)

            set -l current_dns (grep '^nameserver' /etc/resolv.conf | grep -v '^nameserver fe80' | awk '{print $2}' | command tr '\n' ' ' | string trim)

            echo "󰤨 IP:  "(ip -4 addr show | grep -oP 'inet \K[\d.]+' | grep -v '127.0.0.1' | head -1)
            echo "󰉋 DNS: $current_dns"
            echo "$DIM────────────────────────────$RESET"
            set i 1
            for opt in $options
                set name (echo $opt | cut -d'|' -f1)
                set ips (echo $opt | cut -d'|' -f2)
                set first_ip (echo $ips | cut -d' ' -f1)
                if string match -q "*$first_ip*" $current_dns
                    echo "  [$i] $GREEN$name$RESET $DIM($ips)$RESET"
                else
                    echo "  [$i] $name $DIM($ips)$RESET"
                end
                set i (math $i + 1)
            end
            echo "$DIM  [0] 󰜺 exit$RESET"
            read -P "→ " choice

            if test "$choice" = "0" -o -z "$choice"
                echo "󰜺 cancelled"
                return 0
            end

            if not string match -qr '^\d+$' $choice; or test $choice -lt 1 -o $choice -gt (count $options)
                echo "󰅙 invalid option"
                sleep 0.8
                clear
                continue
            end

            set selected $options[$choice]
            set ips (echo $selected | cut -d'|' -f2)
            dns (string split ' ' $ips)
            clear
        end
        return
    end

    sudo cp /etc/resolv.conf /etc/resolv.conf.bak
    echo "# Generated by dns" | sudo tee /etc/resolv.conf > /dev/null
    for server in $argv
        echo "nameserver $server" | sudo tee -a /etc/resolv.conf > /dev/null
    end
    echo "󰉋 DNS: "$argv
end
# ─────────── wifi ───────────
function wifi --description 'Network Manager'
    if not command -v nmcli >/dev/null 2>&1
        echo "󰅙 nmcli not found. Installing..."
        sudo pacman -S --noconfirm networkmanager
    end

    while true
        clear
        set -l PURPLE (set_color cba6f7)
        set -l GREEN (set_color green)
        set -l RED (set_color red)
        set -l DIM (set_color brblack)
        set -l RESET (set_color normal)

        set -l ssid (nmcli -t -f active,ssid dev wifi 2>/dev/null | grep '^yes' | cut -d: -f2)
        set -l ip (ip -4 addr show | grep -oP 'inet \K[\d.]+' | grep -v '127.0.0.1' | head -1)
        set -l dns (grep '^nameserver' /etc/resolv.conf | grep -v '^nameserver fe80' | awk '{print $2}' | command tr '\n' ' ')
        set -l wifi_dev (nmcli -t -f device,type dev | grep wifi | cut -d: -f1 | head -1)

        echo ""
        echo "$PURPLE󰤨 WiFi$RESET"
        echo "$DIM────────────────────────────$RESET"

        if test -n "$ssid"
            set -l freq (nmcli -t -f active,chan dev wifi | grep '^yes' | cut -d: -f2)
            if test -n "$freq"
                if test $freq -le 14
                    set -l band "2.4GHz"
                else
                    set -l band "5GHz"
                end
            else
                set -l band ""
            end

            set -l ping_ms ""
            set -l gw (ip route | grep default | awk '{print $3}' | head -1)
            if test -n "$gw"
                set -l raw_ping (ping -c 1 -W 1 $gw 2>/dev/null | grep -oP 'time=\K[\d.]+')
                if test -n "$raw_ping"
                    set ping_ms " 󰓅 "$raw_ping"ms"
                end
            end

            echo "$GREEN󰄬 $ssid$RESET  $DIM$ip  $band$ping_ms$RESET"
        else
            echo "$RED󰤭 not connected$RESET"
        end

        echo "$DIM󰉋 $dns$RESET"
        echo ""

        set -l networks (nmcli -t -f ssid,signal,security,chan dev wifi list 2>/dev/null | grep -v '^:' | sort -t: -k2 -rn | awk -F: '!seen[$1]++ && $1!=""')

        if test (count $networks) -eq 0
            echo "󰅙 no networks found"
            echo ""
            read -P "→ press enter to retry, 0 to exit: " choice
            if test "$choice" = "0"
                return 0
            end
            continue
        end

        set -l i 1
        set -l ssids
        for net in $networks
            set -l name (echo $net | cut -d: -f1)
            set -l signal (echo $net | cut -d: -f2)
            set -l security (echo $net | cut -d: -f3)
            set -l chan (echo $net | cut -d: -f4)

            if test $signal -ge 75
                set -l bar "▂▄▆█"
            else if test $signal -ge 50
                set -l bar "▂▄▆ "
            else if test $signal -ge 25
                set -l bar "▂▄  "
            else
                set -l bar "▂   "
            end

            if test -z "$security" -o "$security" = "--"
                set -l lock ""
            else
                set -l lock "󰌾 "
            end

            if test -n "$chan" -a "$chan" -le 14 2>/dev/null
                set -l band "2.4G"
            else
                set -l band "5G  "
            end

            if test "$name" = "$ssid"
                printf "$GREEN  [%d] %-30s %s %s $DIM%s$GREEN %s$RESET\n" $i "$name" "$bar" "$lock" "$band" ""
            else
                printf "  [%d] %-30s $DIM%s %s %s$RESET\n" $i "$name" "$bar" "$lock" "$band"
            end

            set ssids $ssids "$name"
            set i (math $i + 1)
        end

        echo ""
        echo "$DIM  [d] disconnect  [r] refresh  [p] passwords  [f] forget all  [0] exit$RESET"
        echo ""
        read -P "→ choice: " choice

        switch $choice
            case 0 ''
                return 0
            case d
                if test -n "$ssid"
                    nmcli dev disconnect $wifi_dev >/dev/null 2>&1
                    echo "× disconnected"
                    sleep 1
                else
                    echo "! not connected"
                    sleep 1
                end
            case r
                nmcli dev wifi rescan 2>/dev/null
            case p
                set -l saved_wifi (nmcli -t -f NAME,TYPE con show 2>/dev/null | grep '802-11-wireless' | cut -d: -f1)
                if test (count $saved_wifi) -eq 0
                    echo "! no saved networks"
                else
                    echo ""
                    for net in $saved_wifi
                        set -l pass (nmcli -s -t -f 802-11-wireless-security.psk con show "$net" 2>/dev/null | cut -d: -f2-)
                        if test -n "$pass"
                            echo "  󰌾 $net: $pass"
                        else
                            echo "  $DIM$net$RESET"
                        end
                    end
                    echo ""
                end
                echo "$DIM  press enter to continue$RESET"
                read cont
            case f
                set -l saved_wifi (nmcli -t -f NAME,TYPE con show 2>/dev/null | grep '802-11-wireless' | cut -d: -f1)
                if test (count $saved_wifi) -eq 0
                    echo "! no saved networks"
                else
                    read -P "󰗜 forget all (count $saved_wifi)? [y/N]: " confirm
                    if string match -qi 'y*' $confirm
                        for net in $saved_wifi
                            nmcli con delete "$net" >/dev/null 2>&1
                        end
                        echo "$RED󰗜 all saved networks forgotten$RESET"
                    else
                        echo "󰜺 cancelled"
                    end
                end
                sleep 1
            case '*'
                if string match -qr '^\d+$' $choice; and test $choice -ge 1 -a $choice -le (count $ssids)
                    set -l target $ssids[$choice]
                    if test "$target" = "$ssid"
                        echo "󰄬 already connected to $target"
                        sleep 1
                        continue
                    end

                    set -l saved (nmcli -t -f name con show 2>/dev/null | grep -Fx "$target")
                    if test -n "$saved"
                        echo "󰤨 connecting to $target..."
                        nmcli con up "$target" >/dev/null 2>&1
                    else
                        read -sP "󰌾 password for $target: " pass
                        echo ""
                        echo "󰤨 connecting to $target..."
                        nmcli dev wifi connect "$target" password "$pass" >/dev/null 2>&1
                    end

                    if test $status -eq 0
                        echo "$GREEN󰄬 connected to $target$RESET"
                    else
                        echo "$RED󰅙 failed to connect$RESET"
                    end
                    sleep 1
                else
                    echo "! invalid option"
                    sleep 0.8
                end
        end
    end
end
